### ISSUE TITLE
Using gitbash instead of putty?

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/genomics-workshop#102]
Let me know if this issue is in the wrong place, I put it here since the setup is here.

I'm wondering if we could have learners with windows use gitbash instead of putty/pscp.  This will make it more similar between windows and mac when we go to download the files for the shell and data wrangling sections.  Then windows users will type the same command in gitbash as mac users type in the terminal.

While we will be giving them a bulkier software, they will be learning out use linux command and then they will be able to use them on their local machines as well.

I'd also be open to using the Ubuntu subsystem but in my latest workshop a bunch of folks didn't have windows 10.  

@SteveGoldstein @maglet @tadamus @sailendharan

**Comment by ErinBecker** [comment]
I would love to have this lesson use gitbash. It would increase consistency with our other lessons. As a Mac user, I don't know the relative strengths and weaknesses of PuTTy vs gitbash and if there was a reason we initially choose PuTTy, I don't know what it is. Maybe @JasonJWilliamsNY can provide some background here and/or let us know if there are any objections to moving forward with this change?

**Comment by fpsom** [comment]
Hi all! In past workshops that had to use cloud resources, I've used all three choices (PuTTy, Gitbash and the Windows Subsystem for Linux) without any issues and with virtually no change to the instructions necessary for use. The "choice flowchart" that I use each time is the following:

* If the participant has **Win10 Pro**, I suggest that they use the WSL and point them to the installation instructions (the official is [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and the more "practical" is [here](https://linuxhint.com/install_ubuntu_windows_10_wsl/) ).

* If they **don't have Win10** Pro (e.g. they have the home version) or if the don't want to really install anything new, I point them towards gitbash. This is not a choice but a rule instead, if the workshop includes some Git lesson as well (obviously not the canonical DC Genomics workshop).

* If they **really don't want to install anything** and there is no Git included in the workshop, the final choice is to download the portable version of PuTTy  ("Alternative binary files" from [here](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) ).

Just my two cents to this conversation... :)

**Comment by sstevens2** [comment]
@fpsom I ended up kind of doing this at the workshop yesterday.  Giving them the 3 options with that same logical flowchart.  Maybe I didn't explain it well but I think it was kind of confusing for folks.  

I'm open to what folks who use Windows more think is best but gitbash has worked really well for me when teaching SWC in the past.

**Comment by ErinBecker** [comment]
I'm happy to change things over to whatever system works best for Windows users, but don't have a Windows machine available easily to test things out myself. In terms of cognitive load, I'd advise whatever solution we implement to be something that can work for all Windows systems (if that exists). @sstevens2 - would you be interested in putting in a PR to the setup instructions based on your experience?

**Comment by sstevens2** [comment]
Made a PR with the install instructions from the workshop webpage template.  I only checked the workshop webpage so there might be changes that are still needed in other parts of the lesson.
