### ISSUE TITLE
genomics-workshop setup page wording a bit confusing

### ISSUE THREAD

**Issue by waydeveldman** [datacarpentry/genomics-workshop#122]
This page https://datacarpentry.org/genomics-workshop/setup.html

Near the top of the page it first says "With the exception of a spreadsheet program, all of the software and data used in the workshop are hosted on an Amazon Machine Image (AMI)", but then under "Required additional software" it says "For Windows, you will also need to install Git Bash, PuTTY, or the Ubuntu Subsystem". 

I propose that we mention the Windows extra requirement with the spreadsheet program requirement? And also, add the word "either" in the phrase "For Windows, you will also need to install **either** Git Bash, PuTTY, or the Ubuntu Subsystem"?

Thank you! :)

**Comment by ErinBecker** [comment]
Thank you for the suggestion @waydeveldman! I've put in a PR to address this issue.
