### ISSUE TITLE
Upgrade AMI to newer version of Ubuntu (from 16.04)

### ISSUE THREAD

**Issue by kerchner** [datacarpentry/genomics-workshop#133]
The current AMI is based on Ubuntu 16.04, which reached the end of its Long-Term Support (LTS) window in April 2021.

I would suggest building a new AMI based on Ubuntu 20+.  This will also facilitate upgrades to R and its packages (see #114)

**Comment by naupaka** [comment]
I think this would be a good idea. The genomics curriculum advisory committee met on October 24, 2022 to discuss best approaches for versioning/updating dependencies and there are some discussions in the works about the best ways to handle this more robustly going forward (e.g. versioned Docker images or etc that could be stable and linked with the archived periodic formal releases of the lessons).

That said, it seems reasonable to me in the short term to update to at least 20.04 (22.04 has some complications e.g. default non-acceptance of RSA keys, docker needing overlay or overlay2 fs vs aufs etc). But maybe we just need to modernize everything to 22.04 now to give a longer stability window going forward?

**Comment by twrightsman** [comment]
This seems to be solved due to the merging of https://github.com/datacarpentry/genomics-workshop/pull/136.
