### ISSUE TITLE
Add common schedules

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/genomics-workshop#138]
From what I've heard people usually teach either the data organization, the unix shell, and data wrangling OR data organization, the unix shell, and the R lesson as both options are about 2 days/4 half days of materials.  I've met with a few instructors teaching this for the first time and they were surprised to hear they couldn't teach all 4 lessons in 2 days/4 half days.  Perhaps we should add a few common schedules to the front page.

1:  data organization, the unix shell, and data wrangling (2 days/ 4 half days)
2: data organization, the unix shell, and the R lesson (2 days/ 4 half days)
2: data organization, the unix shell, data wrangling, and the R lesson (3 days / 6 half days)

**Comment by JCSzamosi** [comment]
I think this is a good idea. Do you think it should be a more detailed breakdown of timings, or just the overview you've described here?

**Comment by sstevens2** [comment]
Thanks for your perspective @JCSzamosi!  Good question! I think maybe a little more detail on how to split the half days would be helpful, I drafted bit more below.

Schedule A(2 days OR 4 half days)
- Half-day 1: data organization, the unix shell, 
- Half-day 2: unix shell (continued)
- Half-day 3 &4 : Data wrangling
Schedule B (2 days OR 4 half days)
- Half-day 1: data organization, the unix shell, 
- Half-day 2: unix shell (continued)
- Half-day 3 &4: R 
Schedule C (3 days OR 6 half days)
- Half-day 1: data organization, the unix shell, 
- Half-day 2: unix shell (continued)
- Half-day 3 &4 : Data wrangling
- Half-day 5&6: R

**Comment by JCSzamosi** [comment]
That looks good to me. I don't think we need to run something like this by the curriculum committee. Do you want to create a pull-request for it?
