### ISSUE TITLE
Do we set up AWS instances for self-organised workshops? 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/genomics-workshop#144]
On this page [https://datacarpentry.org/genomics-workshop/AMI-setup/](https://datacarpentry.org/genomics-workshop/AMI-setup/) we say that users must set up their own instances for self-organised workshops.  However I believe that our Workshop Admin Team does offer these for self-organised workshops.  

Leaving this issue here to consider changing the information here or changing the Workshop Admin Team's workflows.

**Comment by ErinBecker** [comment]
Thanks @maneesha for raising this issue. I'm checking with @sheraaronhurt to confirm the current workflow.

**Comment by sheraaronhurt** [comment]
Thanks @maneesha I was not aware of that being the case. Currently we do offer this service for SOW. I am working on a few things and can address this in upcoming project planning. For now, we will continue to offer this.
