### ISSUE TITLE
Transition to The Carpentries Workbench

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-workshop#147]
Hi @datacarpentry/genomics-workshop-maintainers

The Curriculum Team is preparing to transition all of the workshop/curriculum overview sites to the Workbench. @zkamvar has set **a tentative migration date of Monday 18th September**. This change will bring all of the overview sites, including this one, back in line with all of the official lessons that were transitioned to the new infrastructure in May. 

**What do you need to do?**

To help us prepare for a smooth transition, we invite you to:

1. explore the preview of the transitioned version of the overview site: [PREVIEW_URL](https://fishtree-attempt.github.io/genomics-workshop/)
    - if you find any problems with formatting, missing content, etc, please post a comment on https://github.com/carpentries/lesson-transition/issues/84 to give us the details
1. process any pull requests made to the repository, ensuring that they are all merged or closed before the transition takes place. Any open pull requests on this repository will be invalidated by the transition. There are currently 4 open pull requests on the repository.
1. post the questions and concerns you have about the transition here, tagging @tobyhodges.

**What happens next?**

After the transition, Maintainers will temporarily lose their write access to the repository as a safety measure, ensuring that the old project history cannot be accidentally pushed back into the repository. The steps to restore access are relatively straightforward ([see an example from the completed transition of another lesson](https://github.com/datacarpentry/shell-genomics/issues/336)) and you can expect detailed instructions and further support from the Curriculum Team when the transition takes place.

Beyond that, you can expect to continue maintaining the repository as you were before, while taking advantage of the simplified layout and syntax that the new infrastructure offers. `main` will become the default branch of the repository (currently `gh-pages`), and files currently located in `_extras/` will be divided between two new folders: `learners/` and `instructors/`. You can read more about the changes to repository structure/organisation and source file syntax in [the Workbench Transition Guide](https://carpentries.github.io/workbench/transition-guide.html).

**Comment by tobyhodges** [comment]
@twrightsman I merged #145 today, in preparation for the infrastructure migration. Would you like to merge the other open pull requests before @zkamvar flicks the switch? 

Please let us know because we would like to update the `.zenodo.json` file and make a new release of the repository to Zenodo before the infrastructure transition.

**Comment by twrightsman** [comment]
Alright, the repository is ready for the transition!

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @tracykteal (push)
 - [ ] @naupaka (push)
 - [ ] @jrherr (push)
 - [ ] @shukwong (push)
 - [ ] @JCSzamosi (push)
 - [ ] @hoytpr (push)
 - [ ] @twrightsman (push)
 - [ ] @JasonJWilliamsNY (push)
 - [ ] @anuj2054 (push)
 - [ ] @tobyhodges (admin)
 - [ ] @ggrimes (push)
 - [ ] @ytakemon (push)
 - [ ] @poterlowicz-lab (push)
 - [ ] @rhondene (push)
 - [ ] @hidyverse (push)
 - [ ] @p-j-smith (push)
 - [ ] @alanaschick (push)
 - [ ] @vhmcck (push)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The Workbench version is now live: https://datacarpentry.github.io/genomics-workshop/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/release_dc/genomics-workshop/release/datacarpentry/genomics-workshop-commit-map.hash)

**Comment by twrightsman** [comment]
I am ready for write access :rocket: 

Thanks @zkamvar!!

**Comment by twrightsman** [comment]
Since the transition itself is finished I will close this issue and those who wish to retain their write access can still comment.

**Comment by naupaka** [comment]
I am ready for write access 🚀

**Comment by zkamvar** [comment]
@twrightsman and @naupaka access granted!

**Comment by anuj2054** [comment]
Ready too !

**Comment by zkamvar** [comment]
@anuj2054 access granted!

**Comment by ytakemon** [comment]
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
@ytakemon access granted!

**Comment by JCSzamosi** [comment]
I am ready for write access :rocket:

**Comment by jrherr** [comment]
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
@jrherr access granted!

**Comment by vhmcck** [comment]
Thanks, @zkamvar!

I have done the below before. Can you please check and tell me if I need to do it again?

_If you wish to regain write access, please re-clone the repository on your machine and
then comment here with I am ready for write access :rocket: and the
admin maintainer of this repository will restore your permissions._

Cheers,
Valentina

**Comment by tobyhodges** [comment]
@vhmcck the instructions refer to any forks and clones you have of this repository. I think you have taken these steps before with a different lesson repo (https://github.com/datacarpentry/shell-genomics/). We do need you to repeat the steps and confirm again for the genomics workshop overview site here.

**Comment by vhmcck** [comment]
@tobyhodges thank you very much for clarifying. 

There was some confusion in the past about the two genomics lessons. As per discussed with @ErinBecker:

- @p-j-smith and I will be maintaining this one:https://github.com/datacarpentry/shell-genomics
- The lesson overview (https://github.com/datacarpentry/genomics-workshop) will be maintained by a different group.
