### ISSUE TITLE
Note who will be responsible for providing AWS 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/genomics-workshop#154]
### How could the content be improved?

The [FAQ](https://datacarpentry.org/genomics-workshop/faq#how-will-my-learners-get-connection-and-log-in-information) says that the  Carpentries Workshop and Logistics Manager will provide connection information. This should be updated to whoever is now responsible for this.  Tagging @sheraaronhurt

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/genomics-workshop/faq#how-will-my-learners-get-connection-and-log-in-information

**Comment by sheraaronhurt** [comment]
Made updates

**Comment by twrightsman** [comment]
Fixed in https://github.com/datacarpentry/genomics-workshop/pull/156, thanks everyone!
