### ISSUE TITLE
Lesson / episode order not ideal

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-workshop#26]
There are some structural problems with the ordering of the lessons and of episodes within lessons. For example: in the pipeline workflow workshop, "Project Organization and Management: Project Organization" comes before "Introduction to the Command Line" yet includes several shell commands. 

It would be very helpful to have a flow chart or list showing all of the dependencies among lessons and episodes so that we can do the reordering in a way that makes sense.  Is anyone up for creating such a flow chart?

**Comment by tracykteal** [comment]
That is a good way to think about it! Maybe I can start with mapping it out on a physical white board.

**Comment by ErinBecker** [comment]
After having taught this twice now, I think I see how things fit together better. I revised the lesson overviews on the index page to reflect the order that @k8hertweck and I used (to the best of my memory). Other reorganization is happening within the individual lesson. Closing this issue.
