### ISSUE TITLE
Discuss how to present lessons since some could be done locally

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/genomics-workshop#27]
In general these lessons assume that the cloud computing instance is being used, but some of the lessons could be done locally, for instance the shell-genomics lesson. This issue was brought up there

https://github.com/datacarpentry/shell-genomics/issues/48#issuecomment-330175886

We should discuss in the Advisory Committee meeting how this affects how we write the lessons. Can or should there be local option directions for the ones that can be done locally?

@aschuerch @JasonJWilliamsNY

**Comment by ErinBecker** [comment]
Closed with the PRs listed here: https://github.com/datacarpentry/genomics-workshop/issues/31
