### ISSUE TITLE
lesson reorganization

### ISSUE THREAD

**Issue by bluegenes** [datacarpentry/genomics-workshop#41]
We propose some lesson reorganization to facilitate the Genomics workshops. 

**Motivating issue**: `scp` is used to download `fastqc.html` files in the quality trimming lesson in the `Wrangling Genomics` section, but windows users are unable to use `scp`. This has derailed several recently-taught workshops. 

*Proposed changes:*
---

**Setup:**

- Modify Windows setup: use [gitbash] rather than PUTTY. 
  - benefits: enables windows users to use `scp` and use a bash-style terminal to navigate their own computers.

**Cloud Genomics:**

- Split into two parts:

  - Part 1: Introduction to Remote Computing
     - Lessons:  1 (Why of cloud computing), 2 (Logging onto Cloud) & `whoami` (from 3): 
     - Teach after **Organization Genomics** but before **Shell Genomics**
   
  - Part 2: Remote Computing Strategies (?)
     - Lessons: 3 (Fine tuning your cloud setup), 5 (Which Cloud for my data)
     - Teach at ~end of workshop
     - reasoning: these lessons are confusing at the beginning, when users just need to get going on a remote command line, but are great for helping users go beyond the workshop and start working with their own data/setups
     - If we do this, should we modify Data Roundtripping (lesson 4)? It is partially taught within wrangling genomics (see below)
   
**Wrangling Genomics:**

*Quality control lesson (lesson 1)*: 

- Streamline by removing loops from this lesson (too many concepts here):
   - In ‘Understanding FastQC’ just unzip one thing and look at the text file 
   - After ‘Running FastQC’ section, skip to ‘Understanding FastQC Output'
- Keep `scp` command to download the HTML from FastQC (works in gitbash on Windows)
   - This is half of Data Roundtripping (from cloud section)
   - Can use this as an opportunity to discuss the structure of `scp`-style commands (e.g. `cp`, `mv`, `ln -s`): `scp [origin/file] [destination]`, since they'll have learned these commands in Shell Genomics.
- Revise or eliminate the "Documenting our Work" section
  - Too much in this lesson & we didn't think this was the best way to document work. Automation lesson may be a better spot to discuss documenting work (see below)
  - If we take this out, we should show `cat` to concatenate files together elsewhere (Shell Genomics uses `cat` to join files to stdout, but does not actually `cat` files together).

*Trimming and Filtering (lesson 2):*  
- Add intro to `for` loops  (eliminated from QC - can move some of that section here)
- We already use a `for` loop for trimming files with `Trimmomatic` = we are discussing them anyway. While loops aren't strictly necessary for understanding FastQC output in the QC lesson, we definitely need them for the trimming.

*Variant Calling Workflow (lesson 3)*  
- No changes, just a note that this lesson also uses `scp`

*Automating a Variant Calling Workflow (lesson 4):*

- Better spot for "Documenting Our Work" discussion? (eliminated from QC)
- Could do the 2nd half of `Data Roundtripping`:
   - `scp` script to home computer
   - use nano to add some additional comments to improve documentation 
   - `scp` script back to remote server

Proposed reorganization reflects discussion w/ @tracykteal, @standage, @ljcohen, @karenword @jessicamizzi

**Comment by tracykteal** [comment]
Thanks @bluegenes. Since this would touch a few lessons, we'll talk about this at the Genomics Advisory Committee level. If we do decide to go forward, this same set of people who proposed have said we can implement.

**Comment by rachelss** [comment]
I actually like PuTTY better for students who have never done any command-line work. I would at least provide this as an option. Also, provide an option for Chromebook users.

**Comment by taylorreiter** [comment]
@brooksph recommended the Google Chrome Secure Shell recently as another option as well!

Has the Genomics Advisory Committee had time to talk about implementation? We're teaching the lesson at Davis on June 26 and I would love to use the updated version! PuTTY/scp caused a lot of problems when we taught it here in January.

**Comment by JasonJWilliamsNY** [comment]
Putty is very lightweight and a small file size. Never had problems teaching with it, and when necessary pscp.exe.

**Comment by ErinBecker** [comment]
The CAC will be meeting on 24th and 25th September. I will make sure that this issue is on their agenda.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/wrangling-genomics/pull/133
