### ISSUE TITLE
New workshop data set

### ISSUE THREAD

**Issue by standage** [datacarpentry/genomics-workshop#42]
Thread https://github.com/datacarpentry/wrangling-genomics/issues/111 brings up the concern that `bwa aln` is not appropriate for data the vast majority of our learners will be working with in their own research. In a similar vein, the data set itself is comprised of 1x35bp single-end reads. I propose that this module is updated with more recent data.

Here is an example: [SRA accession SRR2584858](https://www.ncbi.nlm.nih.gov/sra/?term=SRR2584858). These are 2x101bp paired-end reads sequenced from *E. coli* with the HiSeq 2000 platform and published in 2016. Using the same reference genome as before, this particular data set results in 4 SNV calls and a single INDEL call from the variant calling workflow.

Note, I haven't checked this data for poly-N content, which is an important consideration given its relevance to the file search and redirection sections in the shell-genomics module.

**Comment by taylorreiter** [comment]
The paper is here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4988878/

**Comment by JasonJWilliamsNY** [comment]
This would be a nice update. Needs to be coordinated at the level of the curriculum committee.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/wrangling-genomics/pull/133
