### ISSUE TITLE
parallel-fastq-dump

### ISSUE THREAD

**Issue by mgalland** [datacarpentry/genomics-workshop#52]
Dear lesson maintainers, 
I have already participated to one genomics workshop in Amsterdam together with Anita Schürch, 
Dennis Schmitz and Sam Nooij.

I would like to suggest a small addition that could improve the "Examining Data on the NCBI SRA Database" (`organization-genomics/03-ncbi-sra`). I found it easy and much useful for beginners to show that  NCBI SRA datasets can be rapidly downloaded using the `parallel-fastq-dump`tool (https://github.com/rvalieris/parallel-fastq-dump). 

Do you think this would be a small but substantial improvement to that lesson part?  

All the best,
Marc

**Comment by ErinBecker** [comment]
Thank you for the suggestion @mgalland and I'm sorry for the absurdly late response. @taylorreiter has recently led a large set of changes to the lessons that included some changes to how the data is accessed. @taylorreiter could you please let me know if this issue still applies with the new workflow? If so, I'll make sure it gets migrated over to the appropriate lesson repo.

**Comment by mgalland** [comment]
Better late than never! Hope that is included in the new lesson. I'm curious to see the new version ;-)

**Comment by ErinBecker** [comment]
@mgalland - I wanted to make sure the appropriate people are aware of this issue, so I've cross-posted to the organization-genomics lesson repo and am closing here.
