### ISSUE TITLE
Update timeline for Genomics in R lesson release

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/genomics-workshop#54]
The [website](https://datacarpentry.org/lessons/#genomics-workshop) currently says 

> Please note that workshop materials for working with Genomics data in R are under development and will become available in June 2018.

**Comment by ErinBecker** [comment]
Good catch @maneesha - can you please update to October? The Maintainers are actively working on the lessons and have end of August as their release goal, but October will give us some wiggle room. No workshop requests for this curriculum yet right?

**Comment by maneesha** [comment]
Fixed with
https://github.com/datacarpentry/datacarpentry.github.io/commit/cb7ac4689c7cb910b538f0467099f5b5bda66255
