### ISSUE TITLE
Genomic workshop software versions

### ISSUE THREAD

**Issue by orchid00** [datacarpentry/genomics-workshop#57]
I think it is worth adding the version of all the software used in this lesson. [Setup](https://datacarpentry.org/genomics-workshop/setup.html)

**Why?**
To be able to replicate and to make sure a custom setup doesn't differ too much to avoid problems encounter when using different version.

**Background**
This question came up when testing the Amazon Web Service instance for this lesson
The instance has Trimmomatic-0.32, however the [setup](https://datacarpentry.org/genomics-workshop/setup.html) lists Trimmomatic-0.36. I'm unsure how much these two versions differ. Can anyone who has taught the Genomics workshop recently using the AWS confirm that everything works well?

Pinging @ErinBecker @JasonJWilliamsNY @tracykteal to look into this

**Comment by fpsom** [comment]
This is a fair point @orchid00 ! @taylorreiter and others have proposed a major overhaul of the workshop in Issue #53 , and I think it also addresses the issue of software versions!

**Comment by ErinBecker** [comment]
Thanks @orchid00! Closed with https://github.com/datacarpentry/genomics-workshop/commit/f0ffa229310a673d97903eff9c2b3e5c52e773ac#diff-2cc0b07f42930e4520820be1fe66f913
