### ISSUE TITLE
what needs to be on the Amazon image

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/genomics-workshop#6]
For this workshop we'll need an Amazon image that we can use. What needs to be on that image?
- FastQC
- Trimmomatic
- R (plan is to work with this locally, but good to have a backup if needed)
- RStudio (plan is to work with this locally, but good to have a backup if needed)
- a standard text editing program like nano

Anything else?

**Comment by JasonJWilliamsNY** [comment]
* Desktop enabled Ubuntu w/vnc (for visual apps)
* Dropbox? iCommands? or some utility for file transfer (beyond scp and rsync)

**Comment by gawbul** [comment]
Could always have RStudio Server running in the AMI so people can access that remotely instead of having to configure X forwarding/VNC etc.? Otherwise something like [X2Go ](http://wiki.x2go.org/doku.php) might help for the GUI stuff?

**Comment by ErinBecker** [comment]
I believe that this issue has been resolved. The AWS instance that I used for my last workshop included everything that was needed for the workshop. @tracykteal can you please confirm and close?

**Comment by tracykteal** [comment]
Yes, the current AMI matches these lessons. If we want to make changes to datasets or directory structures, we'll need to update the AMI. We can close this issue though.
