### ISSUE TITLE
module on how to get reference genomes?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/genomics-workshop#8]
It might be good to include a module on how to get reference genomes, or at least have pointers to materials on how to do this. This is often a place where people get stuck.

**Comment by ErinBecker** [comment]
The commit referenced above (fix #8) does not appear to be relevant here.

**Comment by ErinBecker** [comment]
@tracykteal Can you please comment as to whether this module exists now, is still in development, or if it has been decided not to include a module like this? Also, this issue should be moved to the appropriate repo where that module would go.

**Comment by tracykteal** [comment]
We do have a module on using NCBI SRA in the 'organization' lesson, so we can close this issue here.
