### ISSUE TITLE
update post-workshop assessment

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/genomics-workshop#9]
I updated the standard post-workshop survey to better reflect the genomics lessons. There's still too much emphasis on R/Python in the 'attitudes' section Question 56 though. What attitudes are we hoping will change? What do we want to ask about?

[Standard_Data_Carpentry_Genomics_Post-Workshop_Survey.docx](https://github.com/datacarpentry/genomics-workshop/files/1098/Standard_Data_Carpentry_Genomics_Post-Workshop_Survey.docx)

**Comment by ErinBecker** [comment]
This issue is outdated. A new post-workshop assessment has been created and is now active for all DC workshops.
